# Generated by Django 4.2.1 on 2023-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.TextField()),
                ('necklace_points', models.IntegerField()),
                ('necklace_abilities', models.TextField()),
                ('earrings1_points', models.IntegerField()),
                ('earrings1_abilities', models.TextField()),
                ('earrings2_points', models.IntegerField()),
                ('earrings2_abilities', models.TextField()),
                ('rings1_points', models.IntegerField()),
                ('rings1_abilities', models.TextField()),
                ('rings2_points', models.IntegerField()),
                ('rings2_abilities', models.TextField()),
                ('ability_stone_rarity', models.IntegerField()),
                ('ability_stone_points', models.IntegerField()),
                ('ability_stone_abilities', models.TextField()),
                ('engraving_slots_points', models.TextField()),
                ('engraving_slot1_abilities', models.TextField()),
                ('engraving_slot2_abilities', models.TextField()),
                ('points_distribution', models.TextField()),
                ('character_class', models.CharField(max_length=200)),
            ],
        ),
    ]
