# Generated by Django 4.2.1 on 2023-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Build',
        ),
    ]
